rules:
# some example rules
    world:
        - Do not swearing
        - Do not kidnap other people's animals
    creative:
        - Random build will be cleared each months
motd:
    joinmessage: "&2Hello &Y%s&2, welcome to &YYourServerName"
    pingmessage: "&YType &r/rules&Y upon joined!"
messages:
    norules: "&2There are no rules for this world!"
    rulestitle: "&2Rules for world &Y%s"